/* This file was automatically generated on Wed 12 Jun 2013 15:29:41 BST from
 * source: /dls_sw/prod/R3.14.11/support/aravisGigE/0-1-15dls6/etc/makeIocs/example.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

