#!/bin/sh
# This file was automatically generated on Fri 25 Feb 2011 13:34:27 GMT from
# source: /dls_sw/prod/R3.14.11/support/firewireDCAM/1-8/etc/makeIocs/example.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(dirname "$0")"
./example stexample.boot
