# This file was automatically generated on Tue 19 Jul 2011 16:02:20 BST from
# source: /dls_sw/prod/R3.14.11/support/aravisGigE/0-1-10/etc/makeIocs/example.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
< envPaths
cd "$(TOP)"

epicsEnvSet "EPICS_TS_MIN_WEST", '0'


# Loading libraries
# -----------------

# Device initialisation
# ---------------------

cd "$(TOP)"

dbLoadDatabase "dbd/example.dbd"
example_registerRecordDeviceDriver(pdbbase)

# aravisCameraConfig(portName, cameraName, maxBuffers, maxMemory)
aravisCameraConfig("CAM1", "Allied Vision Technologies-02-2165A-06632", 50, -1)

# NDStdArraysConfigure(portName, queueSize, blockingCallbacks, NDArrayPort, NDArrayAddr, maxMemory)
NDStdArraysConfigure("ARR1", 2, 0, "CAM1", 0, -1)

# Final ioc initialisation
# ------------------------
cd "$(TOP)"
dbLoadRecords 'db/example_expanded.db'
iocInit
